

2024-02-10T14:12:16.026Z - Error occurred: TypeError [ERR_INVALID_ARG_TYPE]: The "callback" argument must be of type function. Received type number (1000)
